### ISSUE TITLE
Error with coreprocessor.py

### ISSUE THREAD

**Issue by qarlosalberto** [benreynwar/pyvivado#2]
Hello,

Im having this error:

```
cruiz@carlos-pc:~/repositorio/pyvivado/tests$ python3.5 test_project.py 
Traceback (most recent call last):
  File "test_project.py", line 6, in <module>
    from pyvivado import config, base_project, vivado_project
  File "/usr/local/lib/python3.5/dist-packages/pyvivado/vivado_project.py", line 6, in <module>
    import fusesoc_generators
  File "/usr/local/lib/python3.5/dist-packages/fusesoc_generators/__init__.py", line 1, in <module>
    from fusesoc_generators import utils
  File "/usr/local/lib/python3.5/dist-packages/fusesoc_generators/utils.py", line 5, in <module>
    from fusesoc_generators import coreprocessor
  File "/usr/local/lib/python3.5/dist-packages/fusesoc_generators/coreprocessor.py", line 15, in <module>
    from fusesoc import section
ImportError: cannot import name 'section'
```

Do you know what is the problem?

Thank you.

**Comment by benreynwar** [comment]
I'll take a look at this tonight.

**Comment by benreynwar** [comment]
The problem was that fusesoc_generators had a dependency on >= fusesoc 1.7, but was not compatible with fusesoc 1.8.  I just pushed a commit that should make it work with fusesoc 1.8.

Thanks for letting me know of the problem.
